

# Site settings
url: http://cryptowampum.com/
canonical: http://cryptowampum.com/
baseurl: 
title: Wampum eCommerce for All
email: russell@cryptowampum.com
description: "Wampum software allows your business to do commerce electronically, without a local bank account."
headerimg: LocalJoePOS.jpg
headerimg_sm: LocalJoePOS_sm.jpg
logo: /img/logos/WampumLogoTransSm.png


# Team names, titles and social links
people:
- name: Russell Castagnaro
  pic: RussellSqAloha
  position: CEO & Cofounder
  profile: Russell is a visionary whose vast technical knowledge and practical, people-centric approach over the last 23 years has enabled the teams he has led to change the landscape of electronic commerce, enterprise software development and government operations.  
  social:
    - title: twitter
      url: http://twitter.com/rcastag
    - title: facebook
      url: https://www.facebook.com/rcastagnaro
    - title: linkedin
      url: https://www.linkedin.com/in/russell-castagnaro-6231553/

- name: Matthew Skoda
  pic: MattSqAloha
  position: CTO & Cofounder
  profile: Matthew has vast experience in military, ecommerce, cryptography and government technology solutions.  
  social:




# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/cryptowampum
  - title: facebook
    url: https://facebook.com/cryptowampum


# Postal address (add as many lines as necessary)
address:
  - line: 1110 Nuuanu Ave
  - line: #40
  - line: Honolulu, HI 96817

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: compressed
  
compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false
  profile: false
  startings: all
  